#!/bin/sh

repo = "https://overflowlinux.github.io/core-repo/"

do_install(){
    wget $repo/$1
    flow install $1 $2
}
do_remove(){
    flow remove $1 $2
}
do_help(){
    echo "stream install <package> <root> TO INSTALL PACKAGE"
    echo "stream remove <package> <root> TO REMOVE PACKAGE"
    echo "stream help TO PRINT THIS HELP MESSAGE"
}
if [ $UID -ne 0 ];then
    echo "Stream Package Manager Only Run In Root Account."
    exit 0
fi
if [ -n "$1" ];then
    if [ "$1" = "install" ];then
        do_install $2 $3
        exit 0
    fi
    if [ "$1" = "remove" ];then
        do_remove $2 $3
        exit 0
    fi
    if [ "$1" = "help" ];then
        do_help
        exit 0
    fi
    echo "Args are illegal."
fi
